/**
 * PERFUME PARADISE — Clover API Integration Layer
 * ================================================
 *
 * SETUP REQUIRED BEFORE GOING LIVE:
 * Replace the placeholder values below with real credentials
 * obtained from your Clover Developer account and SKU IQ dashboard.
 *
 * Step-by-step instructions are in CLOVER-SETUP-GUIDE.md
 *
 * ⚠️ SECURITY WARNING:
 * Never expose your Clover API token in client-side JavaScript
 * that is deployed to a public website. In production you MUST
 * proxy all Clover API calls through your own backend server
 * (Node.js / PHP / etc.) so credentials stay server-side.
 * The structure below shows WHAT to call; the actual calls
 * should be made from your backend.
 */

// ── REAL CREDENTIALS: create js/clover-config.local.js (gitignored) ──
// window.__CLOVER_MERCHANT_ID = 'live-value';
// window.__CLOVER_API_TOKEN   = 'live-value';
// window.__SKUIQ_SECRET       = 'live-value';
// Load that file BEFORE this one in your HTML. Do NOT edit this file.
const CloverConfig = {
  MERCHANT_ID:          (typeof __CLOVER_MERCHANT_ID  !== 'undefined') ? __CLOVER_MERCHANT_ID  : 'YOUR_CLOVER_MERCHANT_ID',
  API_TOKEN:            (typeof __CLOVER_API_TOKEN    !== 'undefined') ? __CLOVER_API_TOKEN    : 'YOUR_CLOVER_API_TOKEN',
  SKUIQ_WEBHOOK_SECRET: (typeof __SKUIQ_SECRET        !== 'undefined') ? __SKUIQ_SECRET        : 'YOUR_SKUIQ_WEBHOOK_SECRET',
  ENV: 'sandbox',  // Change to 'production' when going live
};

const CLOVER_BASE = {
  sandbox:    'https://apisandbox.dev.clover.com',
  production: 'https://api.clover.com',
};

/**
 * CloverAPI
 *
 * All methods here are stubs showing what the real integration looks like.
 * Replace the mock returns with actual fetch() calls to your backend proxy.
 *
 * Backend proxy example (Node/Express):
 *   app.get('/api/products', async (req, res) => {
 *     const r = await fetch(`${CLOVER_BASE}/v3/merchants/${mId}/items?...`, {
 *       headers: { Authorization: `Bearer ${API_TOKEN}` }
 *     });
 *     res.json(await r.json());
 *   });
 */
const CloverAPI = {

  /* ── PRODUCTS / INVENTORY ────────────────────────────────────────── */

  /**
   * Fetch all inventory items from Clover.
   * Clover endpoint: GET /v3/merchants/{mId}/items
   *
   * @returns {Promise<Array>} Array of products in our internal format
   */
  async getProducts() {
    /* === REPLACE WITH REAL CALL ===
    const res = await fetch(`/api/products`);       // Your backend proxy
    const data = await res.json();
    return data.elements.map(this._mapCloverItem);
    */

    // Stub: fall back to sample data during development
    console.info('[Clover] getProducts() — using sample data. Add credentials to go live.');
    return window.ProductService.getAll();
  },

  /**
   * Fetch a single item by Clover item ID.
   * Clover endpoint: GET /v3/merchants/{mId}/items/{itemId}
   */
  async getProductById(id) {
    /* === REPLACE WITH REAL CALL ===
    const res = await fetch(`/api/products/${id}`);
    const item = await res.json();
    return this._mapCloverItem(item);
    */
    return window.ProductService.getById(id);
  },

  /**
   * Fetch real-time stock level for an item.
   * SKU IQ syncs Clover inventory — query via:
   * Clover endpoint: GET /v3/merchants/{mId}/item_stocks/{itemId}
   */
  async getStockLevel(itemId) {
    /* === REPLACE WITH REAL CALL ===
    const res = await fetch(`/api/stock/${itemId}`);
    const data = await res.json();
    return { qty: data.quantity, inStock: data.quantity > 0 };
    */
    console.info('[Clover] getStockLevel() — using sample data');
    return { qty: 10, inStock: true };
  },

  /* ── ORDERS ──────────────────────────────────────────────────────── */

  /**
   * Create an order in Clover from cart contents.
   * Clover endpoint: POST /v3/merchants/{mId}/orders
   * Then add line items: POST /v3/merchants/{mId}/orders/{orderId}/line_items
   *
   * @param {Object} cartOrder  Output of Cart.toCloverOrder()
   * @param {Object} customer   { firstName, lastName, email, phone }
   * @returns {Promise<{orderId: string, orderNumber: string}>}
   */
  async createOrder(cartOrder, customer) {
    /* === REPLACE WITH REAL CALL ===
    const res = await fetch('/api/orders', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ cartOrder, customer })
    });
    return res.json();
    */

    // Stub: generate a fake order number for demo
    const orderId = 'ORD-' + Date.now().toString(36).toUpperCase();
    console.info('[Clover] createOrder() — demo mode, order ID:', orderId);
    return { orderId, orderNumber: orderId, success: true };
  },

  /* ── PAYMENTS ────────────────────────────────────────────────────── */

  /**
   * Initialize Clover's hosted iFrame payment form.
   * This inserts Clover's JavaScript SDK into the page which renders
   * a PCI-compliant card entry form inside an iframe.
   *
   * Clover SDK docs: https://docs.clover.com/docs/clover-iframe-integrations
   *
   * Call this inside your checkout page after the DOM is ready.
   * @param {string} containerId  ID of the div where the iframe renders
   */
  initPaymentForm(containerId) {
    /* === REPLACE WITH REAL IMPLEMENTATION ===
    const clover = new Clover(CloverConfig.API_TOKEN, {
      merchantId: CloverConfig.MERCHANT_ID
    });
    const elements = clover.elements();
    const cardNumber = elements.create('CARD_NUMBER');
    const cardDate   = elements.create('CARD_DATE');
    const cardCvv    = elements.create('CARD_CVV');
    const cardZip    = elements.create('CARD_POSTAL_CODE');

    cardNumber.mount('#card-number');
    cardDate.mount('#card-date');
    cardCvv.mount('#card-cvv');
    cardZip.mount('#card-zip');

    // On form submit, tokenize the card:
    // const { token } = await clover.createToken();
    // Send token to your backend to charge via Clover Payments API
    */

    const container = document.getElementById(containerId);
    if (!container) return;
    container.innerHTML = `
      <div class="payment-placeholder">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5z"/>
        </svg>
        <h4>Secure Payment via Clover</h4>
        <p>Payment processing will appear here once your Clover credentials are configured.<br>
        See <strong>CLOVER-SETUP-GUIDE.md</strong> for setup instructions.</p>
      </div>
    `;
  },

  /* ── DATA MAPPING ────────────────────────────────────────────────── */

  /**
   * Map a Clover API item response to our internal product format.
   * Customize field names to match your Clover item attributes.
   */
  _mapCloverItem(cloverItem) {
    return {
      id:               cloverItem.id,
      sku:              cloverItem.sku ?? '',
      name:             cloverItem.name,
      brand:            cloverItem.alternateName ?? 'Unknown Brand',   // Store brand in alternateName
      price:            (cloverItem.price ?? 0) / 100,                 // Clover stores cents
      salePrice:        null,
      description:      cloverItem.description ?? '',
      shortDescription: cloverItem.description?.slice(0, 80) ?? '',
      category:         cloverItem.categories?.elements?.[0]?.name?.toLowerCase() ?? 'unisex',
      scentFamily:      'unknown',    // Use a custom label/tag in Clover for scent family
      sizes:            [],           // Use Clover item variants for size options
      inStock:          (cloverItem.itemStock?.quantity ?? 1) > 0,
      stockQuantity:    cloverItem.itemStock?.quantity ?? 0,
      image:            cloverItem.imageUrl ?? null,
      featured:         false,
      isNew:            false,
      tags:             []
    };
  }
};

window.CloverAPI = CloverAPI;
window.CloverConfig = CloverConfig;
